config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end
  root to: "restaurants#index"

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include WithUserAssociationExtension
  validates :name, length: {minimum: 3}, uniqueness: true
  belongs_to :user
  has_many :reviews, dependent: :destroy

  def build_review(attributes = {}, user)
    attributes[:user] ||= user
    reviews.build(attributes)
  end
end
  def average_rating
    return 'N/A' if reviews.none?
    reviews.inject(0) {|memo, review| memo + review.rating} / reviews.length
  end

app/models/review.rb
class Review < ActiveRecord::Base

  has_many :endorsements, dependent: :destroy
  belongs_to :user
  belongs_to :restaurant
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :restaurants
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name
      # user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
          user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end
end

app/models/with_user_association_extension.rb
module WithUserAssociationExtension
  def create_with_user(attributes = {}, user)
   attributes[:user] ||= user
   create(attributes)
  end

  def create_with_user!(attributes = {}, user)
    attributes[:user] ||= user
    create!(attributes)
  end

  def build_with_user(attributes = {}, user)
    attributes[:user] ||= user
    build(attributes)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    redirect_to restaurants_path
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include WithUserAssociationExtension
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
    @reviews = Review.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.user_id == current_user.id
      @restaurant.destroy
      flash[:notice] = 'Restaurant deleted successfully'
      redirect_to '/restaurants'
    else
      flash[:notice] = 'Can\'t delete Restaurant, you didn\'t add'
      redirect_to '/restaurants'
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  include WithUserAssociationExtension

  def new
    if current_user.has_reviewed? @restaurant
      flash[:notice] = 'You have already reviewed this restaurant'
    end

    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review(review_params, current_user)
    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        flash[:notice] = 'You have already reviewed this restaurant'
        redirect_to '/restaurants'
      else
        render :new
      end
    end
  end

  def destroy
    @review = Review.find(params[:id])
    p @review.user_id
    p current_user.id
    if @review.user_id == current_user.id
      @review.destroy
      flash[:notice] = 'Review deleted successfully'
      redirect_to '/restaurants'
    else
      flash[:notice] = 'Can\'t delete Review, you didn\'t add'
      redirect_to '/restaurants'
    end
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= yield %>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Facebook Sign in", user_omniauth_authorize_path(:facebook) %>
<% end %>

</body>
</html>

app/views/restaurants/edit.html.haml
= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <h3>Reviews for <%= restaurant.name %></h3>
    <% if restaurant.reviews.any? %>
      <ul>
        <% restaurant.reviews.each do |review| %>
        <%= link_to "Delete review", review_path( review), method: :delete %>
        <p><%= pluralize review.endorsements.count, 'endorsement' %> </p> <%= link_to "Endorse Review", review_endorsements_path(review), method: :post %>

          <li>
            <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
            <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
          </li>
        <% end %>
      </ul>
<% else %>
  <p>No reviews.</p>
<% end %>
  <% end %>
   </ul>

<% else %>
  <h1>No restaurants yet</h1>
<% end %>

<a href="/restaurants/new">Add a restaurant</a>

app/views/restaurants/index.html.haml
- if @restaurants.any?
  - @restaurants.each do |restaurant|
    = link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant)
    = link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete
    = link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant)
    = link_to restaurant.name, restaurant_path(restaurant)
    %h3
      Reviews for
      = restaurant.name

    - if restaurant.reviews.any?
      %ul
        - restaurant.reviews.each do |review|
          %li
            = review.thoughts
            %strong= review.rating
            \/5
    - else
      %p No reviews

- else
  %h1 No restaurants yet!

%a(href='/restaurants/new') Add Restaurant

app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>


<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/new.html.haml
- if @restaurant.errors.any?
  %section#errors
    %h2
      = pluralize @restaurant.errors.count, "error"
      prohibited this restaurant from being saved:
    %ul
      - @restaurant.errors.full_messages.each do |message|
        %li= message

= form_for @restaurant do |f|
  = f.label :name
  = f.text_field :name
  = f.submit

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>

<p><%= @restaurant.description %></p>

app/views/restaurants/show.html.haml
%p= @restaurant.name
%p= @restaurant.description

%h3
  Reviews for
  = @restaurant.name

- if @restaurant.reviews.any?
  %ul
    - @restaurant.reviews.each do |review|
      %li
        = review.thoughts
        %strong= review.rating
        \/5
- else
  %p No reviews

app/views/reviews/new.html.erb
  <%= form_for [@restaurant, @review] do |f| %>
    <%= f.label :thoughts %>
    <%= f.text_area :thoughts %>
    <%= f.label :rating %>
    <%= f.select :rating, (1..5) %>
    <%= f.submit 'Leave Review' %>
  <% end %>

app/views/reviews/new.html.haml
= form_for [@restaurant, @review] do |f|
  = f.label :thoughts
  = f.text_area :thoughts
  = f.label :rating
  = f.select :rating, (1..5)
  = f.submit 'Leave Review'